//! Event-driven backtesting engine with event-driven simulation and performance metrics.
#![warn(missing_docs)]

use quant_core::ohlcv::Bar;
use quant_core::order::Order;
use quant_core::price::Quantity;
use quant_core::symbol::Symbol;
use rust_decimal::Decimal;
use std::collections::HashMap;

/// A trading signal generated by a strategy.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Signal {
    /// Enter long.
    Long,
    /// Enter short.
    Short,
    /// Exit / flatten.
    Flat,
    /// No action.
    Hold,
}

/// A trading strategy for backtesting.
pub trait Strategy: Send + Sync {
    /// Strategy name.
    fn name(&self) -> &str;
    /// Process a new bar and optionally emit a signal.
    fn on_bar(&mut self, bar: &Bar, portfolio: &Portfolio) -> Signal;
    /// Reset strategy state.
    fn reset(&mut self);
}

/// A position in the backtest portfolio.
#[derive(Debug, Clone, PartialEq)]
pub struct Position {
    /// Symbol.
    pub symbol: Symbol,
    /// Quantity (positive long, negative short).
    pub quantity: Quantity,
    /// Average entry price.
    pub avg_entry_price: Decimal,
    /// Unrealized PnL.
    pub unrealized_pnl: Decimal,
}

/// Portfolio state during backtesting.
#[derive(Debug, Clone, Default)]
pub struct Portfolio {
    /// Cash balance.
    pub cash: Decimal,
    /// Positions by symbol.
    pub positions: HashMap<String, Position>,
    /// Total realized PnL.
    pub realized_pnl: Decimal,
    /// Total number of trades.
    pub trade_count: u64,
}

impl Portfolio {
    /// Create a portfolio with starting cash.
    pub fn with_cash(cash: Decimal) -> Self {
        Self {
            cash,
            ..Default::default()
        }
    }

    /// Total equity (cash + position values).
    pub fn equity(&self) -> Decimal {
        let position_value: Decimal = self
            .positions
            .values()
            .map(|p| p.quantity.decimal() * p.avg_entry_price + p.unrealized_pnl)
            .sum();
        self.cash + position_value
    }

    /// Is the portfolio flat (no positions)?
    pub fn is_flat(&self) -> bool {
        self.positions.is_empty()
    }
}

/// Backtest engine configuration.
#[derive(Debug, Clone, PartialEq)]
pub struct BacktestConfig {
    /// Initial cash.
    pub initial_cash: Decimal,
    /// Commission per trade (fraction, e.g., 0.001 for 0.1%).
    pub commission_rate: Decimal,
    /// Slippage model (fraction).
    pub slippage: Decimal,
    /// Allow short selling.
    pub allow_short: bool,
}

impl Default for BacktestConfig {
    fn default() -> Self {
        Self {
            initial_cash: Decimal::from(100_000),
            commission_rate: Decimal::new(1, 3), // 0.1%
            slippage: Decimal::new(5, 4),        // 0.05%
            allow_short: false,
        }
    }
}

/// Backtest engine that runs a strategy over historical bars.
#[derive(Debug)]
pub struct BacktestEngine {
    config: BacktestConfig,
    portfolio: Portfolio,
    orders: Vec<Order>,
}

impl BacktestEngine {
    /// Create a new backtest engine.
    pub fn new(config: BacktestConfig) -> Self {
        Self {
            portfolio: Portfolio::with_cash(config.initial_cash),
            config,
            orders: Vec::new(),
        }
    }

    /// Run a strategy over a series of bars.
    pub fn run<S: Strategy>(&mut self, strategy: &mut S, bars: &[Bar]) -> BacktestResult {
        strategy.reset();
        self.portfolio = Portfolio::with_cash(self.config.initial_cash);
        self.orders.clear();

        for bar in bars {
            let signal = strategy.on_bar(bar, &self.portfolio);
            self.execute_signal(signal, bar);
        }

        // Mark positions to market using the last bar's close price
        if let Some(last_bar) = bars.last() {
            for pos in self.portfolio.positions.values_mut() {
                pos.unrealized_pnl =
                    pos.quantity.decimal() * (last_bar.close - pos.avg_entry_price);
            }
        }

        BacktestResult {
            final_equity: self.portfolio.equity(),
            total_return: self.portfolio.equity() - self.config.initial_cash,
            realized_pnl: self.portfolio.realized_pnl,
            trade_count: self.portfolio.trade_count,
            max_drawdown: Decimal::ZERO, // TODO: implement
            sharpe_ratio: None,          // TODO: implement
        }
    }

    fn execute_signal(&mut self, signal: Signal, bar: &Bar) {
        match signal {
            Signal::Long => {
                // Simplified: buy 1 share at close price
                let price = bar.close * (Decimal::ONE + self.config.slippage);
                let qty = Quantity::from_decimal(Decimal::ONE);
                // Deduct cash
                self.portfolio.cash -= qty.decimal() * price;
                self.portfolio.trade_count += 1;
                // Create position (simplified)
                let position = Position {
                    symbol: Symbol::new("SYM", quant_core::symbol::InstrumentType::Stock),
                    quantity: qty,
                    avg_entry_price: price,
                    unrealized_pnl: Decimal::ZERO,
                };
                self.portfolio.positions.insert("SYM".into(), position);
            }
            Signal::Short if self.config.allow_short => {
                // Simplified short logic
            }
            _ => {}
        }
    }

    /// Current portfolio.
    pub fn portfolio(&self) -> &Portfolio {
        &self.portfolio
    }
}

/// Backtest performance metrics.
#[derive(Debug, Clone, PartialEq)]
pub struct BacktestResult {
    /// Final portfolio equity.
    pub final_equity: Decimal,
    /// Total return (absolute).
    pub total_return: Decimal,
    /// Realized PnL.
    pub realized_pnl: Decimal,
    /// Number of trades executed.
    pub trade_count: u64,
    /// Maximum drawdown (peak to trough).
    pub max_drawdown: Decimal,
    /// Annualized Sharpe ratio (if computable).
    pub sharpe_ratio: Option<Decimal>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[derive(Debug)]
    struct BuyAndHold;

    impl Strategy for BuyAndHold {
        fn name(&self) -> &str {
            "BuyAndHold"
        }
        fn on_bar(&mut self, _bar: &Bar, portfolio: &Portfolio) -> Signal {
            if portfolio.is_flat() {
                Signal::Long
            } else {
                Signal::Hold
            }
        }
        fn reset(&mut self) {}
    }

    fn make_bars() -> Vec<Bar> {
        vec![
            Bar::new(
                0,
                Decimal::from(100),
                Decimal::from(100),
                Decimal::from(100),
                Decimal::from(100),
                1,
            ),
            Bar::new(
                1,
                Decimal::from(100),
                Decimal::from(110),
                Decimal::from(100),
                Decimal::from(110),
                1,
            ),
            Bar::new(
                2,
                Decimal::from(110),
                Decimal::from(120),
                Decimal::from(110),
                Decimal::from(120),
                1,
            ),
        ]
    }

    #[test]
    fn buy_and_hold_generates_return() {
        let mut engine = BacktestEngine::new(BacktestConfig::default());
        let mut strategy = BuyAndHold;
        let result = engine.run(&mut strategy, &make_bars());

        assert!(result.final_equity > engine.config.initial_cash);
        assert_eq!(result.trade_count, 1);
    }
}
