//! # Strategy Pattern
//!
//! ## Financial Rationale
//!
//! A trading platform must support diverse strategies: trend following,
//! mean reversion, statistical arbitrage, factor models, ML-based, etc.
//! The Strategy pattern decouples the strategy interface from concrete
//! implementations, allowing strategies to be selected at runtime,
//! composed, and backtested uniformly.
//!
//! ## Rust Adaptation
//!
//! Rust's trait system is the natural fit for the Strategy pattern.
//! We define a `Strategy` trait with a single `evaluate` method.
//! Concrete strategies implement this trait. Object safety is maintained
//! by keeping the trait methods simple (no generics).
//!
//! ## Performance Note
//!
//! Using `&dyn Strategy` (trait objects) incurs a vtable dispatch cost.
//! For hot paths (e.g., HFT strategies), prefer `impl Strategy` or
//! monomorphized generics. This crate uses `&dyn` for flexibility in
//! backtesting engines where strategy selection is dynamic.

use std::fmt::Debug;

/// A market snapshot used as input to strategy evaluation.
///
/// In a real system this would contain order book depth, recent trades,
/// indicators, and alternative data. Here we keep it minimal for clarity.
#[derive(Debug, Clone, PartialEq)]
pub struct MarketContext {
    /// Current mid-price.
    pub price: f64,
    /// 24h volume.
    pub volume: f64,
    /// Timestamp (unix millis).
    pub timestamp: i64,
}

/// A trading signal generated by a strategy.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Signal {
    /// Enter long position.
    Long,
    /// Enter short position.
    Short,
    /// Flatten / exit position.
    Flat,
    /// No action.
    Hold,
}

/// Core strategy trait.
///
/// Implementors receive market context and emit a signal.
/// The trait is object-safe (no generic methods or `Self: Sized` bounds).
pub trait Strategy: Debug + Send + Sync {
    /// Human-readable strategy name.
    fn name(&self) -> &str;

    /// Evaluate the strategy given current market context.
    fn evaluate(&self, ctx: &MarketContext) -> Signal;

    /// Reset any internal state (useful for backtesting multiple runs).
    fn reset(&mut self);
}

// ------------------------------------------------------------------
// Concrete Strategy: Simple Moving Average Crossover
// ------------------------------------------------------------------

/// Moving Average Crossover strategy.
///
/// Generates a `Long` signal when the fast MA crosses above the slow MA,
/// and `Short` when it crosses below. Uses a simple ring buffer for
/// price history.
#[derive(Debug, Clone)]
pub struct MovingAverageCrossover {
    name: String,
    fast_period: usize,
    slow_period: usize,
    pub prices: Vec<f64>,
    last_signal: Signal,
}

impl MovingAverageCrossover {
    /// Create a new MA crossover strategy.
    ///
    /// # Panics
    ///
    /// Panics if `fast_period >= slow_period`.
    pub fn new(fast_period: usize, slow_period: usize) -> Self {
        assert!(
            fast_period < slow_period,
            "fast_period must be < slow_period"
        );
        Self {
            name: format!("MA_Crossover_{fast_period}_{slow_period}"),
            fast_period,
            slow_period,
            prices: Vec::with_capacity(slow_period),
            last_signal: Signal::Hold,
        }
    }

    fn fast_ma(&self) -> f64 {
        let window = self.prices.iter().rev().take(self.fast_period);
        let sum: f64 = window.sum();
        sum / self.fast_period as f64
    }

    fn slow_ma(&self) -> f64 {
        let window = self.prices.iter().rev().take(self.slow_period);
        let sum: f64 = window.sum();
        sum / self.slow_period as f64
    }
}

impl Strategy for MovingAverageCrossover {
    fn name(&self) -> &str {
        &self.name
    }

    fn evaluate(&self, _ctx: &MarketContext) -> Signal {
        if self.prices.len() < self.slow_period {
            return Signal::Hold;
        }
        let fast = self.fast_ma();
        let slow = self.slow_ma();

        if fast > slow && self.last_signal != Signal::Long {
            return Signal::Long;
        }
        if fast < slow && self.last_signal != Signal::Short {
            return Signal::Short;
        }
        Signal::Hold
    }

    fn reset(&mut self) {
        self.prices.clear();
        self.last_signal = Signal::Hold;
    }
}

// ------------------------------------------------------------------
// Concrete Strategy: Mean Reversion (Bollinger Band touch)
// ------------------------------------------------------------------

/// Simple mean-reversion strategy based on z-score threshold.
#[derive(Debug, Clone)]
pub struct MeanReversion {
    name: String,
    lookback: usize,
    z_threshold: f64,
    prices: Vec<f64>,
}

impl MeanReversion {
    /// Create a new mean reversion strategy.
    ///
    /// `z_threshold` is the number of standard deviations from the mean
    /// that triggers a signal.
    pub fn new(lookback: usize, z_threshold: f64) -> Self {
        Self {
            name: format!("MeanReversion_{lookback}_{z_threshold}"),
            lookback,
            z_threshold,
            prices: Vec::with_capacity(lookback),
        }
    }
}

impl Strategy for MeanReversion {
    fn name(&self) -> &str {
        &self.name
    }

    fn evaluate(&self, ctx: &MarketContext) -> Signal {
        if self.prices.len() < self.lookback {
            return Signal::Hold;
        }
        let mean = self.prices.iter().sum::<f64>() / self.prices.len() as f64;
        let variance =
            self.prices.iter().map(|p| (p - mean).powi(2)).sum::<f64>() / self.prices.len() as f64;
        let std = variance.sqrt();
        if std == 0.0 {
            return Signal::Hold;
        }
        let z = (ctx.price - mean) / std;

        if z < -self.z_threshold {
            Signal::Long // Price is low, expect reversion up
        } else if z > self.z_threshold {
            Signal::Short // Price is high, expect reversion down
        } else {
            Signal::Hold
        }
    }

    fn reset(&mut self) {
        self.prices.clear();
    }
}

// ------------------------------------------------------------------
// Strategy Registry (Factory + Strategy combined)
// ------------------------------------------------------------------

use std::collections::HashMap;

/// Registry of named strategies. Allows runtime selection.
#[derive(Default)]
pub struct StrategyRegistry {
    strategies: HashMap<String, Box<dyn Strategy>>,
}

impl StrategyRegistry {
    /// Create an empty registry.
    pub fn new() -> Self {
        Self::default()
    }

    /// Register a strategy under a name.
    pub fn register(&mut self, name: impl Into<String>, strategy: Box<dyn Strategy>) {
        self.strategies.insert(name.into(), strategy);
    }

    /// Retrieve a strategy by name.
    pub fn get(&self, name: &str) -> Option<&dyn Strategy> {
        self.strategies.get(name).map(|b| b.as_ref())
    }

    /// Evaluate all registered strategies and return their signals.
    pub fn evaluate_all(&self, ctx: &MarketContext) -> Vec<(&str, Signal)> {
        self.strategies
            .iter()
            .map(|(name, strat)| (name.as_str(), strat.evaluate(ctx)))
            .collect()
    }
}

// ------------------------------------------------------------------
// Tests
// ------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn ctx(price: f64) -> MarketContext {
        MarketContext {
            price,
            volume: 1_000_000.0,
            timestamp: 0,
        }
    }

    #[test]
    fn ma_crossover_generates_signals() {
        let mut strat = MovingAverageCrossover::new(2, 5);
        // Seed prices: uptrend (fast will be above slow)
        for i in 1..=5 {
            strat.prices.push(i as f64);
        }
        strat.last_signal = Signal::Short; // Force change
        let signal = strat.evaluate(&ctx(6.0));
        assert_eq!(signal, Signal::Long);
    }

    #[test]
    fn mean_reversion_buy_on_low_z() {
        let mut strat = MeanReversion::new(5, 1.5);
        // Prices with variance centered around 100
        for i in 0..5 {
            strat.prices.push(90.0 + i as f64 * 5.0); // 90, 95, 100, 105, 110
        }
        let signal = strat.evaluate(&ctx(80.0)); // well below mean
        assert_eq!(signal, Signal::Long);
    }

    #[test]
    fn mean_reversion_sell_on_high_z() {
        let mut strat = MeanReversion::new(5, 1.5);
        for i in 0..5 {
            strat.prices.push(90.0 + i as f64 * 5.0); // 90, 95, 100, 105, 110
        }
        let signal = strat.evaluate(&ctx(120.0)); // well above mean
        assert_eq!(signal, Signal::Short);
    }

    #[test]
    fn registry_evaluates_multiple() {
        let mut reg = StrategyRegistry::new();
        reg.register("ma", Box::new(MovingAverageCrossover::new(2, 5)));
        reg.register("mr", Box::new(MeanReversion::new(5, 1.5)));

        let results = reg.evaluate_all(&ctx(100.0));
        assert_eq!(results.len(), 2);
    }
}
